PORT: "8080"
DB_HOST: "localhost"
DB_PORT: "5432"
DB_USERNAME: "user"
DB_PASSWORD: "password"
DB_NAME: "postgres"
DB_SSL_MODE: "disable"
PASSWORD_HASH_SALT: "salt"
JWT_SECRET_KEY: "secret"
JWT_ACCESS_TOKEN_EXPIRATION_SECONDS: 900
JWT_REFRESH_TOKEN_EXPIRATION_SECONDS: 86400
COOKIE_SECURE: false
COOKIE_MAX_AGE_SECONDS: 86400